homepage.about-us.heading: "Über uns"
homepage.about-us.numbers.heading: "Our company in numbers"
homepage.about-us.numbers.01: "Qualified<br>employees"
homepage.about-us.numbers.02: "Satisfied<br>customers"
homepage.about-us.numbers.03: "Pieces<br>per year"
homepage.gallery.heading: "We offer precision<br>without compromise."
homepage.contact.heading: "Get in touch"
homepage.contact.button.all: "All contacts"

contacts.contact-us: "Kontaktieren Sie uns"
contacts.card.01.job: "Produktionsleiter"
contacts.card.02.job: "Verkaufsleiter"
contacts.card.03.job: "Bestellungen<span>/</span>Buchhaltung"
contacts.card.04.quality: "Qualität"
contacts.account-number: "Kontonummer"
contacts.registered: "Registergericht in Hradec Králové, Sec. C, File 33993"
contacts.form.heading: "Schreiben Sie uns"
contacts.map.heading: "Wo finden Sie uns"

manufacturing.machinery-equipment: "Maschinenausrüstung"
manufacturing.turning.heading: "Drehen"
manufacturing.turning.parameter.01: "max. Durchmesser"
manufacturing.turning.parameter.02: "max. Länge"
manufacturing.turning.parameter.03: "Spindeldurchmesser"
manufacturing.turning.machine.01.desc: "CNC Bearbeitungszentrum - Drehen<br>Metall- und Kunststoffbearbeitung"
manufacturing.turning.machine.02.desc: "CNC Bearbeitungszentrum - Drehen<br>Präzise und effiziente Metallbearbeitung"
manufacturing.turning.machine.03.desc: "CNC Bearbeitungszentrum - Drehen<br>Präzise und effiziente Metallbearbeitung"
manufacturing.milling.heading: "Fräsen"
manufacturing.milling.parameter.01: "Achse x"
manufacturing.milling.parameter.02: "Achse y"
manufacturing.milling.parameter.03: "Achse z"
manufacturing.milling.machine.01.desc: "CNC Bearbeitungszentrum - mahlen<br>Metall- und Kunststoffbearbeitung"
manufacturing.milling.machine.02.desc: "CNC Bearbeitungszentrum - mahlen<br>Präzise und effiziente Metallbearbeitung"
manufacturing.milling.machine.03.desc: "CNC Bearbeitungszentrum - mahlen<br>Präzise und effiziente Metallbearbeitung"
manufacturing.measurement.heading: "Messung"
manufacturing.measurement.machine.01.desc: "CNC Messtechnik im klimatisierten Messraum"
manufacturing.measurement.machine.01.text: "Wir prüfen unsere Werkstücke auf einem Zeiss CONTURA 3D-Messgerät, inklusive der Möglichkeit ein Messprotokoll zu liefern."
manufacturing.other.heading: "Andere  Ausrüstung"
manufacturing.other.text: "In Zusammenarbeit mit unseren Partnern können wir Schweißen, Pressen, Stanzen, Fräsen von großen Abmessungen, Herstellung von Blechteilen anbieten."

surface-finishing.anodizing: "Eloxieren"
surface-finishing.nickel-plating: "Vernickelung"
surface-finishing.galvanizing: "Galvanisieren"
surface-finishing.bluing: "Brünieren"
surface-finishing.laser-description: "Laserbeschreibung"
surface-finishing.nitrieren-hardening: "Nitridace härten"
