homepage.banner.claim: "Flexibilita and kvalita<br>na prvním místě."
homepage.about-us.heading: "O nás"
homepage.about-us.numbers.heading: "Our company in numbers"
homepage.about-us.numbers.01: "Kvalifikovaných<br>zaměstnanců"
homepage.about-us.numbers.02: "Spokojených<br>zákazníků"
homepage.about-us.numbers.03: "Vyrobených<br>kusů ročně"
homepage.gallery.heading: "We offer precision<br>without compromise."
homepage.contact.heading: "Get in touch"
homepage.contact.button.all: "All contacts"

contacts.contact-us: "Kontaktujte nás"
contacts.card.01.job: "Vedoucí výroby"
contacts.card.02.job: "Vedoucí obchodu"
contacts.card.03.job: "Objednávky/<wbr>účetnictví"
contacts.card.04.quality: "Kvalita"
contacts.account-number: "Číslo účtu"
contacts.registered: "Registrováno v obchodním rejstříku u Krajského soudu v Hradci Kralové pod spisovou značkou C 33993"
contacts.form.heading: "Zanechte nám zprávu"
contacts.map.heading: "Kde nás najdete"

manufacturing.machinery-equipment: "Strojní zařízení"
manufacturing.turning.heading: "Soustružení"
manufacturing.turning.parameter.01: "Max. oběh obrobku"
manufacturing.turning.parameter.02: "Maximální délka řezání"
manufacturing.turning.parameter.03: "Průběžné vřeteno max."
manufacturing.turning.machine.01.desc: "CNC Obráběcí centrum - soustružení<br>Obrábění kovů a plastů"
manufacturing.turning.machine.02.desc: "CNC Obráběcí centrum - soustružení<br>Přesné a ekonomické obrábění kovů"
manufacturing.turning.machine.03.desc: "CNC Obráběcí centrum - soustružení<br>Přesné a efektivní obrábění kovů"
manufacturing.milling.heading: "Frézování"
manufacturing.milling.parameter.01: "Osa x"
manufacturing.milling.parameter.02: "Osa y"
manufacturing.milling.parameter.03: "Osa z"
manufacturing.milling.machine.01.desc: "CNC Obráběcí centrum - frézování<br>Obrábění kovů a plastů"
manufacturing.milling.machine.02.desc: "CNC Obráběcí centrum - frézování<br>Přesné a ekonomické obrábění kovů"
manufacturing.milling.machine.03.desc: "CNC Obráběcí centrum - frézování<br>Přesné a efektivní obrábění kovů"
manufacturing.measurement.heading: "Měření"
manufacturing.measurement.machine.01.desc: "CNC měřicí přístroj v klimatizované měřicí místnosti"
manufacturing.measurement.machine.01.text: "Naše obrobky kontrolujeme na 3D měřícím přístroji Zeiss CONTURA, včetně možnosti dodání měrového protokolu. "
manufacturing.other.heading: "Ostatní strojní zařízení"
manufacturing.other.text: "Ve spolupráci s našimi partnery můžeme nabídnout: svařování, lisování, vysekávání, frézování velkých rozměrů, výroba plechových dílů."

surface-finishing.anodizing: "Eloxování"
surface-finishing.nickel-plating: "Niklování"
surface-finishing.galvanizing: "Zinkování"
surface-finishing.bluing: "Brynýrování"
surface-finishing.laser-description: "Popis laserem"
surface-finishing.nitrieren-hardening: "Kalení"

services.service.01.heading: "Konstrukční návrh, výroba, sestavení. Spolupráce při uvedení do provozu."
services.service.02.heading: "Řezání laserem, vysekávání, ohýbání plechů"
