homepage.about-us.heading: "O nás"
homepage.about-us.numbers.heading: "Our company in numbers"
homepage.about-us.numbers.01: "Qualified<br>employees"
homepage.about-us.numbers.02: "Satisfied<br>customers"
homepage.about-us.numbers.03: "Pieces<br>per year"
homepage.gallery.heading: "We offer precision<br>without compromise."
homepage.contact.heading: "Get in touch"
homepage.contact.button.all: "All contacts"

contact.form.name.label: "Name"
contact.form.name.required: "Name is required."
contact.form.email.label: "E-mail"
contact.form.email.required: "E-mail is required."
contact.form.email.format: "Incorrect e-mail address."
contact.form.phone.label: "Phone"
contact.form.text.label: "Your message"
contact.form.gdpr.text: "Odesláním formuláře souhlasím se"
contact.form.gdpr.link: "zpracováním osobních údajů"
contact.form.send: "Send message"

contact.page.contact-us: "Contact us"
contact.page.form.heading: "Write us a message"
contact.page.map.heading: "Where you can find us"

manufacturing.turning.heading: "Soustružení"
manufacturing.turning.parameter.01: "Max. oběh obrobku"
manufacturing.turning.parameter.02: "Maximální délka řezání"
manufacturing.turning.parameter.03: "Průběžné vřeteno max."
manufacturing.turning.machine.01.desc: "CNC Obráběcí centrum - soustružení<br>Obrábění kovů a plastů"
manufacturing.turning.machine.02.desc: "CNC Obráběcí centrum - soustružení<br>Přesné a ekonomické obrábění kovů"
manufacturing.turning.machine.03.desc: "CNC Obráběcí centrum - soustružení<br>Přesné a efektivní obrábění kovů"
manufacturing.milling.heading: "Frézování"
manufacturing.milling.parameter.01: "Osa x"
manufacturing.milling.parameter.02: "Osa y"
manufacturing.milling.parameter.03: "Osa z"
manufacturing.milling.machine.01.desc: "CNC Obráběcí centrum - frézování<br>Obrábění kovů a plastů"
manufacturing.milling.machine.02.desc: "CNC Obráběcí centrum - frézování<br>Přesné a ekonomické obrábění kovů"
manufacturing.milling.machine.03.desc: "CNC Obráběcí centrum - frézování<br>Přesné a efektivní obrábění kovů"

surface-finishing.anodizing: "Anodizing"
surface-finishing.nickeling: "Nickeling"
surface-finishing.galvanizing: "Galvanizing"
surface-finishing.blackening: "Blackening"
surface-finishing.laser-cutting: "Laser cutting"
surface-finishing.quenching: "Quenching"
surface-finishing.painting: "Painting"
