homepage.about-us.heading: "Über uns"
homepage.about-us.numbers.heading: "Our company in numbers"
homepage.about-us.numbers.01: "Qualified<br>employees"
homepage.about-us.numbers.02: "Satisfied<br>customers"
homepage.about-us.numbers.03: "Pieces<br>per year"
homepage.gallery.heading: "We offer precision<br>without compromise."
homepage.contact.heading: "Get in touch"
homepage.contact.button.all: "All contacts"

contact.form.name.label: "Name"
contact.form.name.required: "Name is required."
contact.form.email.label: "E-mail"
contact.form.email.required: "E-mail is required."
contact.form.email.format: "Incorrect e-mail address."
contact.form.phone.label: "Phone"
contact.form.text.label: "Your message"
contact.form.gdpr.text: "Odesláním formuláře souhlasím se"
contact.form.gdpr.link: "zpracováním osobních údajů"
contact.form.send: "Send message"

contact.page.contact-us: "Contact us"
contact.page.form.heading: "Write us a message"
contact.page.map.heading: "Where you can find us"

manufacturing.turning.heading: "Drehen"
manufacturing.turning.parameter.01: "max. Durchmesser"
manufacturing.turning.parameter.02: "max. Länge"
manufacturing.turning.parameter.03: "Spindeldurchmesser"
manufacturing.turning.machine.01.desc: "CNC Bearbeitungszentrum - Drehen<br>Metall- und Kunststoffbearbeitung"
manufacturing.turning.machine.02.desc: "CNC Bearbeitungszentrum - Drehen<br>Präzise und effiziente Metallbearbeitung"
manufacturing.turning.machine.03.desc: "CNC Bearbeitungszentrum - Drehen<br>Präzise und effiziente Metallbearbeitung"
manufacturing.milling.heading: "Mahlen"
manufacturing.milling.parameter.01: "Achse x"
manufacturing.milling.parameter.02: "Achse y"
manufacturing.milling.parameter.03: "Achse z"
manufacturing.milling.machine.01.desc: "CNC Bearbeitungszentrum - mahlen<br>Metall- und Kunststoffbearbeitung"
manufacturing.milling.machine.02.desc: "CNC Bearbeitungszentrum - mahlen<br>Präzise und effiziente Metallbearbeitung"
manufacturing.milling.machine.03.desc: "CNC Bearbeitungszentrum - mahlen<br>Präzise und effiziente Metallbearbeitung"

surface-finishing.anodizing: "Anodizing"
surface-finishing.nickeling: "Nickeling"
surface-finishing.galvanizing: "Galvanizing"
surface-finishing.blackening: "Blackening"
surface-finishing.laser-cutting: "Laser cutting"
surface-finishing.quenching: "Quenching"
surface-finishing.painting: "Painting"
