about-us.heading: "About us"
about-us.numbers.heading: "Our company in numbers"
about-us.numbers.01: "Qualified<br>employees"
about-us.numbers.02: "Satisfied<br>customers"
about-us.numbers.03: "Pieces<br>per year"

gallery.heading: "We offer precision<br>without compromise."

contact.heading: "Get in touch"
contact.button.all: "All contacts"
contact.form.name.label: "Name"
contact.form.name.required: "Name is required."
contact.form.email.label: "E-mail"
contact.form.email.required: "E-mail is required."
contact.form.email.format: "Incorrect e-mail address."
contact.form.phone.label: "Phone"
contact.form.text.label: "Your message"
contact.form.gdpr.text: "Odesláním formuláře souhlasím se"
contact.form.gdpr.link: "zpracováním osobních údajů"
contact.form.send: "Send message"
