homepage.banner.claim: "Flexibility and quality<br>come first."
homepage.about-us.heading: "About us"
homepage.about-us.numbers.heading: "Our company in numbers"
homepage.about-us.numbers.01: "Qualified<br>employees"
homepage.about-us.numbers.02: "Satisfied<br>customers"
homepage.about-us.numbers.03: "Pieces<br>per year"
homepage.gallery.heading: "We offer precision<br>without compromise."
homepage.contact.heading: "Get in touch"
homepage.contact.button.all: "All contacts"

contacts.contact-us: "Contact us"
contacts.card.01.job: "Head of production"
contacts.card.02.job: "Sales manager"
contacts.card.03.quality: "Quality"
contacts.account-number: "Account number"
contacts.registered: "Registered in the Commercial Register of the Municipal Court in Hradec Kralove, Sec. C, File 33993"
contacts.form.heading: "Write us a message"
contacts.map.heading: "Where you can find us"

manufacturing.machinery-equipment: "Machinery equipment"
manufacturing.turning.heading: "Turning"
manufacturing.turning.parameter.01: "Max Part Swing"
manufacturing.turning.parameter.02: "Max Cutting Length"
manufacturing.turning.parameter.03: "Bar Capacity"
manufacturing.turning.machine.01.desc: "CNC Machining center - turning<br>Metal and plastic machining"
manufacturing.turning.machine.02.desc: "CNC Machining center - turning<br>Precise and economical metal machining"
manufacturing.turning.machine.03.desc: "CNC Machining center - turning<br>Precise and efficient metal machining"
manufacturing.milling.heading: "Milling"
manufacturing.milling.parameter.01: "X Axis"
manufacturing.milling.parameter.02: "Y Axis"
manufacturing.milling.parameter.03: "Z Axis"
manufacturing.milling.machine.01.desc: "CNC Machining center - milling<br>Metal and plastic machining"
manufacturing.milling.machine.02.desc: "CNC Machining center - milling<br>Precise and economical metal machining"
manufacturing.milling.machine.03.desc: "CNC Machining center - milling<br>Precise and efficient metal machining"
manufacturing.measurement.heading: "Measurement"
manufacturing.measurement.machine.01.desc: "CNC measurement technology in air-conditioned measuring room"
manufacturing.measurement.machine.01.text: "We check our workpieces on a Zeiss CONTURA 3D measuring device, including the possibility of delivering a measurement protocol."
manufacturing.other.heading: "Other machinery equipment"
manufacturing.other.text: "In cooperation with our partners, we can offer welding, pressing, punching, milling of large dimensions, production of sheet metal parts."

surface-finishing.anodizing: "Anodizing"
surface-finishing.nickel-plating: "Nickel plating"
surface-finishing.galvanizing: "Galvanizing"
surface-finishing.bluing: "Bluing"
surface-finishing.laser-description: "Laser description"
surface-finishing.nitrieren-hardening: "Nitrieren hardening"
