homepage.banner.claim: "Flexibilité et qualité<br>avant tout."
homepage.about-us.heading: "À propos de nous"
homepage.about-us.numbers.heading: "Notre entreprise en chiffres"
homepage.about-us.numbers.01: "Employés<br>qualifiés"
homepage.about-us.numbers.02: "Clients<br>satisfaits"
homepage.about-us.numbers.03: "pièces produites<br>par an"
homepage.gallery.heading: "Nous offrons<br>la précision<br>sans compromis."
homepage.contact.heading: "Contactez"
homepage.contact.button.all: "Tous les contacts"

contacts.contact-us: "Nous contacter"
contacts.card.01.job: "Chef de la production"
contacts.card.02.job: "Directeur commercial"
contacts.card.03.job: "Commande/comptable"
contacts.card.04.quality: "Qualité"
contacts.account-number: "Numéro de compte"
contacts.registered: "Tribunal d'enregistrement Hradec Kralove, Sec. C, File 33993"
contacts.form.heading: "Écrivez-nous un message"
contacts.map.heading: "Où peux-tu nous trouver"

manufacturing.machinery-equipment: "Equipement machines"
manufacturing.turning.heading: "Tournage"
manufacturing.turning.parameter.01: "Diamètre en l’air de la pièce max"
manufacturing.turning.parameter.02: "Longueur de coupe maximal"
manufacturing.turning.parameter.03: "Passage de barre"
manufacturing.turning.machine.01.desc: "CNC Centre d'usinage - tournage<br>Usinage métal et plastique"
manufacturing.turning.machine.02.desc: "CNC Centre d'usinage - tournage<br>Usinage précis et économique des métaux"
manufacturing.turning.machine.03.desc: "CNC Centre d'usinage - tournage<br>Usinage précis et efficace des métaux"
manufacturing.milling.heading: "Fraisage"
manufacturing.milling.parameter.01: "Axe X"
manufacturing.milling.parameter.02: "Axe Y"
manufacturing.milling.parameter.03: "Axe Z"
manufacturing.milling.machine.01.desc: "CNC Centre d'usinage - fraisage<br>Usinage métal et plastique"
manufacturing.milling.machine.02.desc: "CNC Centre d'usinage - fraisage<br>Usinage précis et économique des métaux"
manufacturing.milling.machine.03.desc: "CNC Centre d'usinage - fraisage<br>Usinage précis et efficace des métaux"
manufacturing.measurement.heading: "Measures"
manufacturing.measurement.machine.01.desc: "Technologie de mesure CNC dans une salle de mesure climatisée"
manufacturing.measurement.machine.01.text: "Nous contrôlons nos pièces sur un appareil de mesure Zeiss CONTURA 3D, y compris la possibilité de délivrer un protocole de mesure."
manufacturing.other.heading: "Autre équipement"
manufacturing.other.text: "Nous pouvons travailler en collaboration avec nos partenaires, presses, salles, fraises de grandes dimensions, production de pièces de tôlerie."

surface-finishing.anodizing: "Anodisation"
surface-finishing.nickel-plating: "Nickelage"
surface-finishing.galvanizing: "Galvanisation"
surface-finishing.bluing: "Bleuissage"
surface-finishing.laser-description: "Descriptif laser"
surface-finishing.nitrieren-hardening: "Nitriding trempe"

services.service.01.heading: "Conception structurelle, production, montage. Coopération dans la mise en service."
services.service.02.heading: "Découpe au laser, poinçonnage, pliage de la tôle"
